// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/shared/types/string_message.proto

package types // import "github.com/lpy-neo/grpc-framework/api/proto/shared/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_string_message_89066a59a03781dc, []int{0}
}
func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (dst *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(dst, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*StringMessage)(nil), "types.StringMessage")
}

func init() {
	proto.RegisterFile("api/proto/shared/types/string_message.proto", fileDescriptor_string_message_89066a59a03781dc)
}

var fileDescriptor_string_message_89066a59a03781dc = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0x4d, 0xd1, 0x2f, 0xa9, 0x2c,
	0x48, 0x2d, 0xd6, 0x2f, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x8f, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0xd5, 0x03, 0xab, 0x10, 0x62, 0x05, 0xcb, 0x29, 0xa9, 0x72, 0xf1, 0x06, 0x83, 0xa5, 0x7d,
	0x21, 0xb2, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x10, 0x8e, 0x93, 0x55, 0x94, 0x45, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72,
	0x7e, 0xae, 0x7e, 0x4e, 0x41, 0xa5, 0x6e, 0x5e, 0x6a, 0xbe, 0x7e, 0x7a, 0x51, 0x41, 0xb2, 0x6e,
	0x5a, 0x51, 0x62, 0x6e, 0x6a, 0x79, 0x7e, 0x51, 0xb6, 0x3e, 0x76, 0xeb, 0x93, 0xd8, 0xc0, 0x62,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0xb3, 0xcb, 0xf2, 0x9f, 0x00, 0x00, 0x00,
}
